name: .NET Build with SonarQube

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore dependencies
        run: dotnet restore src/UnitTestAutomation/UnitTestAutomation.csproj

      - name: Build
        run: dotnet build src/UnitTestAutomation/UnitTestAutomation.sln --no-restore

      - name: Run SonarQube Analysis
        run: |
          dotnet sonarscanner begin \
            /k:"UnitTestAutomation" \
            /o:"${{ secrets.SONAR_ORGANIZATION }}" \
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          dotnet build UnitTestAutomation.sln
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"